#!/bin/bash

events="1E6"
de_th_y_45b="0E-6"
de_th_y_45t="0E-6"

seeds_from="6"
seeds_to="10"

base_dir="${events},${de_th_y_45b},${de_th_y_45t}"

#----------------------------------------------------------------------------------------------------

make "simulation" || exit 1

#----------------------------------------------------------------------------------------------------

for seed in `seq $seeds_from $seeds_to`
do
	echo $seed

	mkdir -p "$base_dir/$seed"

	./simulation --seed "$seed" --diagonal "45b_56t" --nEv "$events" --de_th_y "${de_th_y_45b}" \
		--outputDir "$base_dir/$seed" &> "$base_dir/$seed/distributions_45b_56t.log_run" &

	./simulation --seed "$seed" --diagonal "45t_56b" --nEv "$events" --de_th_y "${de_th_y_45t}" \
		--outputDir "$base_dir/$seed" &> "$base_dir/$seed/distributions_45t_56b.log_run" &
done
